In [58]:
import pandas as pd 
import numpy as np

In [59]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [77]:
df=pd.read_csv('D:\\dataset\\covid_reviews_50_ordinal.csv')
df

     Age           City  Gender  Review Has_COVID
0   22.0          Delhi    Male    Good       Yes
1   35.0         Mumbai  Female    Best        No
2   28.0      Bangalore    Male  Normal       Yes
3   41.0      Hyderabad  Female    Best        No
4   19.0           Pune  Female  Normal       Yes
5    NaN        Chennai    Male    Best        No
6   31.0        Kolkata  Female  Normal       Yes
7   45.0         Jaipur    Male    Best        No
8   27.0      Ahmedabad  Female    Good       Yes
9   38.0          Surat    Male    Best        No
10  24.0        Lucknow    Male  Normal       Yes
11  50.0         Indore  Female    Best        No
12  33.0         Bhopal    Male  Normal       Yes
13  29.0         Nagpur  Female    Good        No
14  60.0          Patna    Male  Normal       Yes
15  21.0         Kanpur  Female    Best        No
16  43.0     Chandigarh    Male    Good       Yes
17  36.0          Noida  Female    Best        No
18   NaN        Gurgaon    Male    Good       Yes
19  25.0  Visakhapatnam  Female    Best        No
20  57.0          Delhi    Male  Normal       Yes
21  30.0         Mumbai  Female    Best        No
22  26.0      Bangalore    Male    Good       Yes
23  40.0      Hyderabad  Female    Best        No
24  23.0           Pune    Male  Normal       Yes
25   NaN        Chennai  Female    Best        No
26  34.0        Kolkata    Male    Good       Yes
27  39.0         Jaipur  Female    Best        No
28  46.0      Ahmedabad    Male  Normal       Yes
29  20.0          Surat  Female    Best        No
30  58.0        Lucknow    Male  Normal       Yes
31  32.0         Indore  Female    Good        No
32  37.0         Bhopal    Male  Normal       Yes
33  44.0         Nagpur  Female    Best        No
34  29.0          Patna    Male    Good       Yes
35  53.0         Kanpur  Female    Best        No
36  18.0     Chandigarh    Male  Normal       Yes
37  42.0          Noida  Female    Best        No
38  47.0        Gurgaon    Male    Good       Yes
39  26.0  Visakhapatnam  Female    Best        No
40  51.0          Delhi    Male  Normal       Yes
41  33.0         Mumbai  Female    Best        No
42  24.0      Bangalore    Male    Good       Yes
43  56.0      Hyderabad  Female    Best        No
44  35.0           Pune    Male  Normal       Yes
45  49.0        Chennai  Female    Best        No
46  27.0        Kolkata    Male    Good       Yes
47  38.0         Jaipur  Female    Best        No
48  61.0      Ahmedabad    Male  Normal       Yes
49  31.0          Surat  Female    Best        No

In [78]:
df['Age'] = df['Age'].replace('NaN', np.nan)
df.isnull().sum()

Age          3
City         0
Gender       0
Review       0
Has_COVID    0
dtype: int64

In [101]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['Has_COVID']), 
    df['Has_COVID'], 
    test_size=0.3
)

In [80]:
x_train

     Age           City  Gender  Review
17  36.0          Noida  Female    Best
38  47.0        Gurgaon    Male    Good
31  32.0         Indore  Female    Good
49  31.0          Surat  Female    Best
11  50.0         Indore  Female    Best
44  35.0           Pune    Male  Normal
33  44.0         Nagpur  Female    Best
34  29.0          Patna    Male    Good
26  34.0        Kolkata    Male    Good
32  37.0         Bhopal    Male  Normal
43  56.0      Hyderabad  Female    Best
19  25.0  Visakhapatnam  Female    Best
0   22.0          Delhi    Male    Good
47  38.0         Jaipur  Female    Best
23  40.0      Hyderabad  Female    Best
3   41.0      Hyderabad  Female    Best
48  61.0      Ahmedabad    Male  Normal
27  39.0         Jaipur  Female    Best
29  20.0          Surat  Female    Best
39  26.0  Visakhapatnam  Female    Best
6   31.0        Kolkata  Female  Normal
37  42.0          Noida  Female    Best
9   38.0          Surat    Male    Best
20  57.0          Delhi    Male  Normal
5    NaN        Chennai    Male    Best
36  18.0     Chandigarh    Male  Normal
13  29.0         Nagpur  Female    Good
41  33.0         Mumbai  Female    Best
12  33.0         Bhopal    Male  Normal
28  46.0      Ahmedabad    Male  Normal
25   NaN        Chennai  Female    Best
1   35.0         Mumbai  Female    Best
45  49.0        Chennai  Female    Best
18   NaN        Gurgaon    Male    Good
24  23.0           Pune    Male  Normal

In [81]:
x_test.shape

(15, 4)

1.Aam zindagi

In [102]:
# adding simple imputer on age column
si =SimpleImputer()
x_train_Age=si.fit_transform(x_train[['Age']])
x_test_Age=si.fit_transform(x_test[['Age']])

In [75]:
x_train_Age

array([[19.],
       [24.],
       [38.],
       [24.],
       [53.],
       [20.],
       [18.],
       [29.],
       [36.],
       [40.],
       [55.],
       [32.],
       [61.],
       [21.],
       [58.],
       [26.],
       [33.],
       [49.],
       [27.],
       [31.],
       [23.],
       [45.],
       [47.],
       [29.],
       [28.],
       [35.],
       [33.],
       [27.],
       [56.],
       [60.],
       [35.],
       [57.],
       [38.],
       [41.],
       [22.]])

In [66]:
x_train_Age.shape

(35, 1)

In [103]:

# ordinal on review column 
oe = OrdinalEncoder(categories=[['Normal', 'Good', 'Best']])
x_train_review = oe.fit_transform(x_train[['Review']])
x_test_review = oe.fit_transform(x_test[['Review']])

In [85]:
x_train_review.shape

(35, 1)

In [105]:
# ohe on gender,city
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['Gender','City']])
x_test_gender_city = ohe.fit_transform(x_test[['Gender','City']])
x_train_gender_city.shape

(35, 19)

In [94]:
x_train_gender_city.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0.]])

In [107]:
x_train_transformed=np.concatenate((x_train_Age,x_train_review,x_train_gender_city),axis=1)

In [108]:
x_test_transformed=np.concatenate((x_test_Age,x_test_review,x_test_gender_city),axis=1)

In [109]:
x_train_transformed.shape

(35, 21)

mentos zindagi

In [110]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[
    ('tf1',SimpleImputer(),['Age']),
    ('tf2',OrdinalEncoder(categories=[['Normal','Good','Best']]),['Review']),
    ('tf3',OneHotEncoder(drop='first',sparse_output=False),['Gender','City'])
],remainder='passthrough')

In [111]:
transformer.fit_transform(x_train).shape

(35, 21)