In [62]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
 df=pd.read_csv('customer.csv')
df.sample(4)

    age  gender review education purchased
39   76    Male   Poor        PG        No
41   23    Male   Good        PG       Yes
31   22  Female   Poor    School       Yes
42   30  Female   Good        PG       Yes

In [72]:
# Keeps ALL rows, but filters to columns from index 2 onwards
df = df.iloc[:, 2:]

In [73]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [131]:
from sklearn.model_selection import train_test_split

# Separate your features (X) and target (y) properly, then pass test_size at the end
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.3)

In [132]:
x_train

     review education
47     Good        PG
25     Good    School
30  Average        UG
5   Average    School
33     Good        PG
28     Poor    School
44  Average        UG
45     Poor        PG
41     Good        PG
31     Poor    School
7      Poor    School
42     Good        PG
19     Poor        PG
1      Poor        UG
35     Poor    School
29  Average        UG
9      Good        UG
2      Good        PG
49     Good        UG
4   Average        UG
20  Average    School
46     Poor        PG
27     Poor        PG
40     Good    School
3      Good        PG
10     Good        UG
37  Average        PG
43     Poor        PG
14     Poor        PG
36     Good        UG
39     Poor        PG
13  Average    School
17     Poor        UG
24  Average        PG
15     Poor        UG

In [133]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Good','Average'],['School','UG','PG']])

In [134]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Good', 'Average'], ['School', 'UG', 'PG']])

In [117]:
x_train=oe.transform(x_train)

In [118]:
x_train

array([[2., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.]])

In [119]:
oe.categories_

[array(['Poor', 'Good', 'Average'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [135]:
from sklearn.preprocessing import LabelEncoder

In [136]:
le=LabelEncoder()

In [137]:
le.fit(y_train)

LabelEncoder()

In [138]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [140]:
y_train = le.transform(y_train)

In [141]:
y_test = le.transform(y_test)

In [142]:
y_train

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0])